[package]
name = "nospaceinvaders"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
rand = "0.8.5"
bevy_rapier3d = "0.26.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
